# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chai < Formula
  desc "Keep AI coding agent configs in sync"
  homepage "https://github.com/charliesbot/chai"
  version "0.11.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/charliesbot/chai/releases/download/v0.11.0/chai_darwin_amd64.tar.gz"
      sha256 "33588a828a7a6d22c14832e96ae58f577257e13092ba02224f8ce43daae5387d"

      define_method(:install) do
        bin.install "chai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/charliesbot/chai/releases/download/v0.11.0/chai_darwin_arm64.tar.gz"
      sha256 "4feeae239f2078748845c830413c7082bf56fd93d6f803ce30533289496cc5a2"

      define_method(:install) do
        bin.install "chai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/charliesbot/chai/releases/download/v0.11.0/chai_linux_amd64.tar.gz"
      sha256 "7a298131c2fc546e3914b699698cef254c5943c61035940310876201924ee04c"
      define_method(:install) do
        bin.install "chai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/charliesbot/chai/releases/download/v0.11.0/chai_linux_arm64.tar.gz"
      sha256 "1fbf25355645713eaafe8f101ec3b7735be4382e168a48d2d783ebb4c329d3de"
      define_method(:install) do
        bin.install "chai"
      end
    end
  end
end
