# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chai < Formula
  desc "Keep AI coding agent configs in sync"
  homepage "https://github.com/charliesbot/chai"
  version "0.12.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/charliesbot/chai/releases/download/v0.12.0/chai_darwin_amd64.tar.gz"
      sha256 "6999eb122b3178172bc1ee4942d8596dcbbf162cc9925346835bb165f3867e6c"

      define_method(:install) do
        bin.install "chai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/charliesbot/chai/releases/download/v0.12.0/chai_darwin_arm64.tar.gz"
      sha256 "c6cc31388f829add628eb21aa614cd827238643d49681f02d5937190c9f41e4b"

      define_method(:install) do
        bin.install "chai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/charliesbot/chai/releases/download/v0.12.0/chai_linux_amd64.tar.gz"
      sha256 "f3363795f1da151325fc9fe1fa392128cea815f9317f2c72dd0fcd88fda2c40e"
      define_method(:install) do
        bin.install "chai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/charliesbot/chai/releases/download/v0.12.0/chai_linux_arm64.tar.gz"
      sha256 "8200cdf7d2c2381f85e2cc15df974400c4796e30b20a862d156e96f966850e39"
      define_method(:install) do
        bin.install "chai"
      end
    end
  end
end
