# This file was generated by GoReleaser. DO NOT EDIT.
cask "chai" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "82313854d9f2996e5fb8972bfc78a74af5433fe953ce96949163fa139a7c43b2"
      url "https://github.com/charliesbot/chai/releases/download/v#{version}/chai_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "88d818e1d40fa3d708074344d3ecb3bcb90aae8452f016449023365a4c575067"
      url "https://github.com/charliesbot/chai/releases/download/v#{version}/chai_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9064d09eee75cb8cddc6d5b4c39f087fa77d5e3217243b5861fa301ec3a1dce7"
      url "https://github.com/charliesbot/chai/releases/download/v#{version}/chai_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0c69f82c8088f3ea62cd313dc1355cca7bc9d77dbb94dd263f2d3051da887a19"
      url "https://github.com/charliesbot/chai/releases/download/v#{version}/chai_linux_arm64.tar.gz"
    end
  end

  name "chai"
  desc "Keep AI coding agent configs in sync"
  homepage "https://github.com/charliesbot/chai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chai"

  # No zap stanza required

end
