# This file was generated by GoReleaser. DO NOT EDIT.
cask "chai" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "3193d961fef2e23ddf44e5ae348dd39aa3fcaa6f332bee5ae31e3479b3467337"
      url "https://github.com/charliesbot/chai/releases/download/v#{version}/chai_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8d27eef44f23b229474a2ce6bc9e268bca792a5c20cb92882325f43712604474"
      url "https://github.com/charliesbot/chai/releases/download/v#{version}/chai_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6752ed6cc371e8f6aa9bd329c93439a7602a3197721b76301caf9ba11c633e40"
      url "https://github.com/charliesbot/chai/releases/download/v#{version}/chai_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "10612afa5979ee2ccc94e987f1fb26ae578440fe54b76509054e484e91d228cd"
      url "https://github.com/charliesbot/chai/releases/download/v#{version}/chai_linux_arm64.tar.gz"
    end
  end

  name "chai"
  desc "Keep AI coding agent configs in sync"
  homepage "https://github.com/charliesbot/chai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chai"

  # No zap stanza required

end
