# This file was generated by GoReleaser. DO NOT EDIT.
cask "chai" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "6bc975f17cd98157eb39e266893558415f4f5bac3ec61826fc10f5bc48abbbcd"
      url "https://github.com/charliesbot/chai/releases/download/v#{version}/chai_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3b29952f8a38f30367d28c0840520995d2317b60171c26df326d91bbc455693f"
      url "https://github.com/charliesbot/chai/releases/download/v#{version}/chai_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "52d7ca717c372ed7937508c75ac77fcd8a74c6b04c5be8c90560a9e87b826477"
      url "https://github.com/charliesbot/chai/releases/download/v#{version}/chai_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f9778dde8e5afa990457e1979ed7669f028d10b11fd8c79709c56660f1a2b259"
      url "https://github.com/charliesbot/chai/releases/download/v#{version}/chai_linux_arm64.tar.gz"
    end
  end

  name "chai"
  desc "Keep AI coding agent configs in sync"
  homepage "https://github.com/charliesbot/chai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chai"

  # No zap stanza required

end
